# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  security:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: ${{ secrets.NODE_VERSION }}
    - run: npm install

    - name: Install SonarQube Scanner
      run: npm install -g sonar-scanner
    - name: Run SonarQube Scan
      run: |
        sonar-scanner \
          -Dsonar.projectKey=neha-project \
          -Dsonar.sources=. \
          -Dsonar.host.url='http://13.127.171.28:9000/' \
          -Dsonar.login='squ_7179aebba0859c3cad3751b986b38483845c0a37'
