# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # This is the manual step to add the .NET SDK to the runner's PATH
    # It must be in every workflow file where you need to use dotnet
    - name: Set up .NET
      run: |
        echo "/home/actions-runner/.dotnet" >> $GITHUB_PATH
        echo "Successfully added .NET SDK to PATH"
        dotnet --version
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish -c Release -o deploy

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-api
        path: deploy
